# .github/workflows/docker-publish.yml

name: Publish Docker Image

on:
  push:
    branches: [ docker ]  # Trigger the workflow on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/setup-go@v4
        with: 
          go-version-file: go.mod

    - name: Fetch Tags
        run: |
          git fetch --tags -f
          git describe --abbrev=0

    - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://x.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

    - name: Get the compressor
        run: sudo apt-get update -y ; sudo apt-get install -y upx


      - name: Make all release artifacts
        run: make

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}


    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: xfhg/intercept:${{ steps.get_version.outputs.VERSION }}
